Repository rahul-n18/Student-Library, pull requests merged in 2022-10, with the labels that each got.

#3 I have added some ideas which are necessary for the app.
  Ideas/Create here
Labels: hacktoberfest, hacktoberfest-accepted

#19 fix: Navbar active page color
  code/about.html
  code/contact.html
  code/index.html
  code/js/main.js
  code/project.html
  code/scss/style.scss
  code/service.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#33 Learn frontend
  learn-frontend/learn_frontend.html
  learn-frontend/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#60 Student-Library new UI
  code/about.html
  code/connect.html
  code/css/style.css
  code/index.html
  code/project ideas.html
  code/why us.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#72 Added Resources
  Books/booklist.md
  Books/free-programming-books.md
  Web Developer Resources/courses.md
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#83 Adding DevOps Resources folder
  DevOps Resources/DevOps.md
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#95 Create issue_comment.yml
  .github/workflows/issue_comment.yml
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#107 Add NumPy Hands-On Tutorial for Machine Learning
  Machine Learning Resources/NumpyTut.ipynb
Labels: hacktoberfest-accepted

#131 Added resources for deep learning with top ML stacks
  Machine Learning Resources/ML_book.md
Labels: hactoberfest-2022

#138 Added C++ cheatsheet
  Books/C C++ C#/C++ Cheatsheet.pdf
Labels: hacktoberfest-accepted

#46 Add C++ coding question for separate Data structure
  code/c++/basic_questions/Armstrong.cpp
  code/c++/basic_questions/DecimaltoBinary.cpp
  code/c++/basic_questions/Factorial_Recursion.cpp
  code/c++/basic_questions/Factorial_usingLoop.cpp
  code/c++/basic_questions/Fibonnaci_Recursion.cpp
  code/c++/basic_questions/Fibonnaci_noRecursion.cpp
  code/c++/basic_questions/Palindrome.cpp
  code/c++/basic_questions/PrimeNumber.cpp
  code/c++/basic_questions/Reverse.cpp
  code/c++/basic_questions/SumofDigits.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest-2022

#143 Added a roadmap for backend development
  backend.png
Labels: hacktoberfest-accepted

#145 add two udemy free docker course in the
  Web Developer Resources/courses.md
Labels: hacktoberfest-accepted

#147 Added Knuth Morris Pratt (KMP) Algorithm
  code/c++/basic_questions/KMP.cpp
Labels: hacktoberfest-accepted

#148 Create factorial_recursion.cpp
  code/c++/basic_questions/factorial_recursion.cpp
Labels: hacktoberfest-accepted

#151 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#159 Create DSA sheet
  DSA sheet
Labels: hacktoberfest-accepted
